export const DEMOS_V2 = [
    {
        id: 'AutoCompLite',
        label: 'AutoCompLite',
        tag: '🆒',
        production: 'v1.0',
    },
    {
        id: 'Basket',
        label: 'Basket',
        tag: 'Smart-ish',
        production: 'v1.0',
    },
    {
        id: 'Card',
        label: 'Card',
        tag: 'Dumb',
        production: 'v1.0',
    },
    {
        id: 'DatePicker',
        label: 'DatePicker',
        tag: 'Smart-ish',
        production: 'alpha',
    },
    {
        id: 'Dialog',
        label: 'Dialog',
        tag: 'Smart-ish',
        production: 'v1.0',
    },
    {
        id: 'Editor',
        label: 'Editor',
        tag: 'Smart-ish',
        production: 'v1.0',
    },
    {
        id: 'Excel',
        label: 'Excel',
        tag: 'Dumb',
        production: 'alpha',
    },
    {
        id: 'Icon',
        label: 'Icon',
        tag: 'Dumb',
        production: 'v1.0',
    },
    {
        id: 'List',
        label: 'List',
        tag: 'Dumb',
        production: 'v1.0',
    },
    {
        id: 'Menu',
        label: 'Menu',
        tag: 'Dumb',
        production: 'v1.0',
    },
    {
        id: 'Popover',
        label: 'Popover',
        tag: 'Dumb',
        production: 'alpha',
    },
    {
        id: 'Portal',
        label: 'Portal',
        tag: 'Dumb',
        production: 'alpha',
        disabled: true,
    },
    {
        id: 'Radio',
        label: 'Radio',
        tag: 'Dumb',
        production: 'v1.0',
    },
    {
        id: 'SlidingWindow',
        label: 'SlidingWindow',
        tag: 'Smart-ish',
        production: 'alpha',
    },
    {
        id: 'Stream',
        label: 'Stream',
        tag: 'Smart-ish',
        production: 'alpha',
        disabled: true,
    },

    {
        id: 'Table',
        label: 'Table',
        tag: 'Dumb',
        production: 'v1.0',
    },
    {
        id: 'Tree',
        label: 'Tree',
        tag: 'Dumb',
        production: 'beta',
    },
    {
        id: 'WebWorker',
        label: 'WebWorker',
        tag: 'Smart-ish',
        production: 'alpha',
        disabled: true,
    },
];
